/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PropertyListing {
  'id' : bigint,
  'title' : string,
  'propertyType' : PropertyType,
  'imageBlobIds' : Array<string>,
  'bedrooms' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'ownerPhone' : string,
  'description' : string,
  'amenities' : Array<string>,
  'available' : boolean,
  'address' : string,
  'monthlyRent' : bigint,
  'bathrooms' : bigint,
}
export type PropertyType = { 'pg' : null } |
  { 'house' : null } |
  { 'room' : null } |
  { 'apartment' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPropertyListing' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      PropertyType,
      bigint,
      bigint,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
  'deletePropertyListing' : ActorMethod<[bigint], undefined>,
  'getAllAvailableListings' : ActorMethod<[], Array<PropertyListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListingById' : ActorMethod<[bigint], [] | [PropertyListing]>,
  'getTotalListingsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListingsByMaxRent' : ActorMethod<[bigint], Array<PropertyListing>>,
  'searchListingsByType' : ActorMethod<[PropertyType], Array<PropertyListing>>,
  'searchListingsByTypeAndMaxRent' : ActorMethod<
    [PropertyType, bigint],
    Array<PropertyListing>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];